from .extract_prompts import (
    DEMOGRAPHICS_PROMPT,
    DIAGNOSIS_PROMPT,
    MEDICATION_PROMPT,
    LAB_PROMPT,
    PROCEDURES_PROMPT,
    CONFLICT_CHECK_PROMPT,
    HOSPITAL_COURSE_PROMPT,
)
__all__ = [
    "DEMOGRAPHICS_PROMPT",
    "DIAGNOSIS_PROMPT",
    "MEDICATION_PROMPT",
    "LAB_PROMPT",
    "PROCEDURES_PROMPT",
    "CONFLICT_CHECK_PROMPT",
    "HOSPITAL_COURSE_PROMPT",
]
